### ISSUE TITLE
Image is displaying in zooming mode.

### ISSUE THREAD

**Issue by laxmanrizecorp** [uzysjung/UzysImageCropper#4]
When a select the image in library or take photo the image is full of zooming mode open in cropping section. Image display in the full screen width. I need to display the image in non zooming mode.

**Comment by uzysjung** [comment]
You don't need Zoom Action . remove  'zoomAction'  method

**Comment by emreyanik** [comment]
I think he needs Zoom Action, but he don't want to full zoomed image at crop screen like me. I changed UzysImageCropper.m line63: 
from=> _imageScale = 310/cropSize.width ;
to => _imageScale = 310/_inputImage.size.width ;

works for me. Sorry about my English

**Comment by uzysjung** [comment]
Thanks EmreYanik89
