### ISSUE TITLE
Show black overlay same as UIImagePickerController & keep cropRect area clear as per attached screenshot

### ISSUE THREAD

**Issue by nfs3250** [uzysjung/UzysImageCropper#8]
First of all thanks for the library... It works as per requirement. Just want to know how can I show black overlay same as UIImagePickerController & keep cropRect area clear as per attached screenshot so that selected image portion is clearly visible 

![img_0133](https://cloud.githubusercontent.com/assets/647008/5124883/76fc9ddc-70e3-11e4-9db8-80da0dc980bf.PNG)

**Comment by uzysjung** [comment]
I don't get it. can you be more specific?

**Comment by nfs3250** [comment]
Please have a look at attached screenshot using your code. If I use your code selected image portion is what you see behind the blue background. So what I want to say is instead of blue background, show it as clear color & at the same time show remaining portion of the view with black color with some transparency so that image behind that portion is still visible.
This will clearly tell user that which portion of the image you will get in result.

![ios simulator screen shot nov 21 2014 12 39 54 pm](https://cloud.githubusercontent.com/assets/647008/5138868/eb856d08-717b-11e4-9ba3-ac01c811b422.png)

**Comment by uzysjung** [comment]
Hi, Currently. this libarary need to modify a little in order to support iPhont 6&6 Plus. 

## Anyway. please check  Library / UzysImageCropper.m file

```
    //_cropperView show the view will crop.
    _cropperView = [[UIView alloc] initWithFrame:_cropRect];
    _cropperView.backgroundColor = [UIColor blueColor];
    _cropperView.alpha = 0.5;

    UIImageView *cropimg = [[[UIImageView alloc] initWithImage:[UIImage imageNamed:@"cropperview.png"]] autorelease];
    cropimg.center = _cropperView.center;
    cropimg.alpha = 0.7;
```

---

modify _cropperView using masking

please check this site(http://perrymitchell.net/article/masking_uiview_cgrect/) , you can find uiview mask. 

thanks.
